version: '3'
services:
  backend-server:
    build: ./backend_server
    command: |
      python backend_server/start_server.py
        --host "0.0.0.0"
        --port 8100
    volumes:
      - './:/src'
      - './writing_content:/src/writing_content'
    ports:
      - "8100:8100"
  front-end:
    build: .
    command: yarn serve

    volumes:
      - './src:/src'
    ports:
      - "8080:8080"
